name: Build iOS Dylib
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile Dylib
        run: |
          # دۆزینەوا هەمی فایلێن .cpp د هەر جهەکێ دابن
          FILES=$(find . -name "*.cpp" -not -path "*/.*")
          echo "Files to compile: $FILES"
          
          # دروستکرنا فایلی ب فەرمانا گشتی
          xcrun -sdk iphoneos clang++ -arch arm64 -shared -std=c++11 \
          -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          $FILES -o $(pwd)/MyMod.dylib || echo "Compile failed"
          
          # پشکنین کا فایل دروست بوو یان نا
          ls -R $(pwd) | grep .dylib

      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: My-iPhone-Dylib
          path: ./*.dylib
          if-no-files-found: error
