name: Build iOS Dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -L https://github.com/theos/sdks/archive/master.zip -o sdks.zip
          unzip -q sdks.zip
          mkdir -p $THEOS/sdks
          mv sdks-master/*.sdk $THEOS/sdks/
          rm -rf sdks-master sdks.zip

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          # دۆزینەوەیا جهێ Makefile ئەگەر د ناڤ فۆڵدەرەکێ دا بیت
          PROJECT_PATH=$(find . -name Makefile -exec dirname {} \; | head -n 1)
          if [ -z "$PROJECT_PATH" ]; then
            echo "Error: Makefile not found!"
            exit 1
          fi
          cd "$PROJECT_PATH"
          echo "Building in: $PROJECT_PATH"
          make clean
          make FINALPACKAGE=1

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: My-iPhone-Dylib
          path: |
            **/obj/**/*.dylib
            **/*.dylib
            **/packages/*.deb
