name: Build iOS Dylib
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile Dylib
        run: |
          find . -name "*.cpp" -print0 | xargs -0 xcrun -sdk iphoneos clang++ -arch arm64 -shared -std=c++11 -o MyMod.dylib
          
      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: My-iPhone-Dylib
          path: MyMod.dylib
